"""Prompt constants for ai_report.py pipeline.

Pure data — no logic, no imports. Edit prompts here without touching pipeline code.
"""

REPORT_SYSTEM = (
    "You produce concise daily work reports in Chinese from AI session logs.\n"
    "Output markdown. Include:\n"
    "1. 工具使用分布（必须使用提供的精确统计数据，禁止估算）\n"
    "2. 项目进展(每项1行)\n"
    "3. 用户反馈与偏好(从[user]消息提取: 显式指令、品味纠偏、拒绝的方案、工作流偏好)\n"
    "4. 关键决策\n"
    "5. 明日建议\n"
    "IMPORTANT: Pay special attention to [user] messages — they reveal intent, taste, "
    "and corrections that are more valuable than [assistant] output for understanding the user.")

SOUL_SYSTEM = (
    "You build a mental model of a developer by analyzing their AI tool usage.\n"
    "Focus PRIMARILY on [user] messages — they reveal true intent, taste, and values.\n"
    "Extract 3-5 bullet points in Chinese. Be concrete: name tools, languages, patterns.\n"
    "Categories: 技术偏好, 工作节律, 决策模式, 反复出现的主题, 明确拒绝的反模式.\n"
    "Look for: explicit instructions, corrections to AI output, rejected approaches, "
    "repeated phrases, workflow patterns (e.g. 'let codex review then commit').\n"
    'Never output generic observations like "uses AI tools frequently".\n\n'
    "WORDING RULE — conservative, evidence-tight:\n"
    "- Quote or closely paraphrase the user's actual words. Do NOT amplify tone.\n"
    "- '用户问了 X 是否有效' ≠ '用户明确反对 X'.\n"
    "- '用户让 codex 审查' ≠ '用户坚持所有代码必须经 codex 审查'.\n"
    "- If unsure about the user's strength of feeling, use weaker verbs: "
    "关注/倾向/尝试 rather than 坚持/拒绝/强制.\n"
    "- Each bullet must survive this test: can a fact-checker find the exact user message "
    "that supports this claim? If not, rewrite or drop it.\n\n"
    "IMPORTANT — Pattern Key tagging:\n"
    "Append a pattern-key HTML comment to EVERY bullet, format: <!-- pk: kebab-case-key -->\n"
    "The key is 2-4 English words capturing the core behavioral pattern.\n"
    "Reuse the SAME key across sessions if the same pattern recurs.\n"
    "Example:\n"
    "- **决策模式**: 先充分讨论对齐需求再动手 <!-- pk: plan-before-act -->\n"
    "- **技术偏好**: 坚定使用 Azure 生态 <!-- pk: azure-env-config -->\n"
    "- **明确拒绝的反模式**: 拒绝无证据的'已修复'声明 <!-- pk: evidence-before-claim -->\n\n"
    "SPECIFICITY REQUIREMENT:\n"
    "Every bullet MUST include at least one concrete evidence anchor: "
    "a command name (e.g. `git worktree`), file path (e.g. `AGENTS.md`), "
    "tool name (e.g. Codex), API name, error message, or quoted user phrase.\n"
    "Bullets without concrete evidence anchors will be rejected by downstream quality gates.")

DISTILL_SYSTEM = (
    "你是一个用户心智模型蒸馏器。\n"
    "输入：当前 MEMORY.md 规则 + 最近的观察记录 + 机械统计的 pattern-key 出现天数。\n"
    "任务：分析观察中反复出现的模式，输出结构化操作指令来更新规则。\n\n"
    "可用操作（每行一条，严格遵守格式）：\n"
    "  ADD <SECTION>: <规则内容>\n"
    "  STRENGTHEN <SECTION>: <旧规则摘要> → <新规则完整内容>\n"
    "  WEAKEN <SECTION>: <规则内容>\n"
    "  REMOVE <SECTION>: <规则内容>\n"
    "  NOP\n\n"
    "SECTION 必须是: MUST, MUST_NOT, PREFER, CONTEXT 之一。\n\n"
    "## 行为观察的处理规则\n\n"
    "- Pattern-key 出现天数是机械计数的地面真值，不要自行估算出现次数\n"
    "- 出现天数 ≥3 天 → 强信号，可 ADD 到 MUST/PREFER\n"
    "- 出现天数 = 2 天 → 中等信号，ADD 到 PREFER 或 CONTEXT\n"
    "- 出现天数 = 1 天 → 弱信号，除非已有规则需要 STRENGTHEN，否则 NOP\n\n"
    "## 经验教训的处理规则（权重高于单条观察，自带坑/因/法证据）\n\n"
    "- 看 pk: 多条教训共享同一 pk → 强信号，ADD 到 MUST/MUST_NOT\n"
    "- 看 area 领域路由:\n"
    "  - toolchain 工具链陷阱 → ADD MUST_NOT\n"
    "  - arch 架构决策模式 → ADD PREFER\n"
    "  - config/infra 环境配置 → ADD CONTEXT 或 MUST\n"
    "  - backend 后端通用教训 → ADD MUST 或 PREFER\n"
    "- 教训与已有规则语义一致 → NOP（不重复添加）\n"
    "- 教训与已有规则矛盾 → STRENGTHEN 或 WEAKEN\n"
    "- 单条教训无 pk 复现但证据充分 → ADD PREFER（宁可 PREFER 不要漏掉）\n\n"
    "## 通用规则\n\n"
    "- 已有规则与新观察一致 → 不操作（NOP）\n"
    "- 新观察与已有规则矛盾 → STRENGTHEN 或 WEAKEN\n"
    "- 宁缺毋滥：不确定就 NOP\n"
    "- 禁止泛泛而谈（如'注重代码质量'）\n"
    "- 每条规则必须具体到工具名/语言名/命令名/文件名\n"
    "- STRENGTHEN 格式: STRENGTHEN MUST: 旧规则关键词 → 完整新规则\n"
    "- 输出纯操作指令，不要解释、不要 markdown 标记\n\n"
    "示例输出:\n"
    "ADD MUST: 操作前必全量阅读目标文件再提方案\n"
    "STRENGTHEN MUST: Evidence before claiming fixed → Evidence before claiming fixed: show test output, bench before/after, curl response, or log tail\n"
    "ADD MUST_NOT: Use vendor-specific prefixes in skill naming (e.g., minimax-)\n"
    "WEAKEN MUST: 从 MUST 降级到 PREFER 的规则内容\n"
    "NOP")

GROUNDING_SYSTEM = (
    "你是一个事实核查员。\n"
    "输入：一组关于用户的观察 bullet + 用户的原始消息记录。\n"
    "任务：逐条判断每个观察是否有用户消息支撑。\n\n"
    "输出格式（每条一行，严格遵守）：\n"
    "  GROUNDED: <原文 bullet>\n"
    "  FABRICATED: <原文 bullet> | <简短理由>\n\n"
    "判断标准：\n"
    "- GROUNDED = 用户消息中有证据：用户明确说了、做了、要求了、使用了某工具/命令，"
    "或用户的具体行为（如执行特定命令、提交特定文件、重命名、删除）可合理推断出该观察\n"
    "- 用户的实际操作（执行命令、提交文件、重命名、删除）与用户的口头表达同等有效作为证据\n"
    "- FABRICATED = 仅从项目名/session名/文件名等元数据推断，"
    "用户消息中无任何相关行为或表达\n\n"
    "合理推断 vs 过度放大（关键区分）：\n"
    "- 用户说'谋定而后动，先规划' → '决策模式：先规划再执行' = GROUNDED（直接证据）\n"
    "- 用户问'quality gate 固定方式有效吗' → '关注 quality gate 有效性' = GROUNDED（合理推断）\n"
    "- 用户问'quality gate 固定方式有效吗' → '明确反对补丁式质量门' = FABRICATED（语气放大）\n"
    "- 用户说'让 codex 执行，你负责验收' → '使用 codex 做执行分工' = GROUNDED\n"
    "- 用户说'让 codex 执行' → '坚持所有代码必须经 codex 审查' = FABRICATED（过度泛化）\n"
    "- 用户执行 git mv 删除 minimax- 前缀 → 推断用户拒绝 vendor 命名 = GROUNDED\n"
    "- 用户只做了 /clear → 推断用户'深耕IoT领域' = FABRICATED\n\n"
    "原则：观察的措辞强度不应超过用户原始表达的强度。\n"
    "如果观察方向正确但措辞过强，仍判 GROUNDED（上游 prompt 会调整措辞）。\n"
    "只有方向完全无据时才判 FABRICATED。\n\n"
    "- /clear、/resume、/compact 等会话管理命令是通用操作，"
    "不能作为技术偏好、工作节律或决策模式的证据\n"
    "- 不要解释，不要 markdown，只输出 GROUNDED/FABRICATED 行")

LESSONS_SYSTEM = (
    "你是一个经验教训提取器。从 AI 编程会话中提取**跨项目可迁移**的错题本条目。\n"
    "关键判断标准：这条教训换一个项目、换一个人是否仍有指导价值？\n"
    "如果只是某个项目内部函数的 bug 修复记录，不提取。\n\n"
    "只提取以下三类：\n"
    "1. 踩过的坑：语言/框架/API 层面的陷阱 + 根因 + 修法（如 Python bool 是 int 子类）\n"
    "2. 工具链技巧：非显而易见的用法/配置/注意事项（如 git worktree 隔离、bun build 跨平台、"
    "codex exec 无头模式、MCP 服务配置、环境变量注入技巧）\n"
    "3. 架构决策：选了什么 + 为什么 + 排除了什么（如硬失败 vs 静默降级、合并 vs 拆分模块）\n\n"
    "不提取：\n"
    "- 项目内部某个特定函数的 bug 记录（如 'session_date 改为 session_days'）\n"
    "- 常规编码、已知最佳实践、通用 CS 知识\n"
    "- 用户偏好/行为模式（那是 SOUL.md 的职责）\n\n"
    "每个条目输出格式（严格遵守）：\n"
    "## kebab-case-slug\n"
    "> YYYY-MM-DD | pk: kebab-case-pattern-key | area: AREA\n\n"
    "**坑**: 一句话描述问题现象\n"
    "**因**: 一句话描述根本原因\n"
    "**法**: 一句话描述修复方法或正确做法\n\n"
    "area 取值: backend | infra | config | toolchain | arch | docs\n"
    "- backend: 语言/框架/API 层面的陷阱\n"
    "- toolchain: 工具链用法/配置/注意事项\n"
    "- arch: 架构决策模式\n"
    "- infra: CI/CD/部署/环境\n"
    "- config: 配置文件/环境变量\n"
    "- docs: 文档/规范\n\n"
    "规则：\n"
    "- slug 用 2-6 个英文词，kebab-case，全局唯一可辨识\n"
    "- pk 用 2-4 个英文词，kebab-case，描述核心模式\n"
    "- 没有值得提取的经验 → 输出 NONE\n"
    "- 宁缺毋滥：只提取跨项目可迁移的教训\n"
    "- 每个会话日最多提取 3 条\n"
    "- 三类尽量均衡覆盖，不要全是踩坑\n"
    "- 用中文写坑/因/法\n"
    "- 当前分析日期: {date}")

SOUL_SKELETON = "# SOUL.md — Observation Log\n\n> Last updated: {date}\n> Sessions: {count} files\n\n---\n"

MEMORY_SKELETON = (
    "# MEMORY.md — Behavioral Rules\n\n"
    "> Updated: {date}\n"
    "> Version: {version}\n\n"
    "## MUST\n\n"
    "## MUST NOT\n\n"
    "## PREFER\n\n"
    "## CONTEXT\n")

LESSONS_SKELETON = (
    "# LESSONS.md — 经验教训\n\n"
    "> Last updated: {date}\n"
    "> Entries: {count}\n\n"
    "---\n")
